id: PCB6407BC
initial_creation_type: ocr
source_metadata:
  volumes:
    08df1978041f4dc0a73c2cc3c68829d0:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ཡེ་ཤེས་མགོན་པོ་གྲི་གུག་ཅན་གྱི་བདག་བསྐྱེད་བཟླས་པ་བསྟོད་པ་རྣམས།
      total_pages: 1464
      volume_number: 47
